baseurl = "http://example.com/"
relativeURLs = false
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-geo"
disqusShortname = "shortcode-here"
paginate = 5


[taxonomies]
    tag = "tags"
    tutorial = "tutorials"

[params]
    showglobe = true
    
    analytics = "code-here"

    github = "https://github.com/luanlv"
    twitter = "#"
    linkedin = "#"
    email = "luanlv2591@gmail.com"
    
    profilepic = "img/profile.png"
    
    title = "VnGuy"
    subtitle = "Technology & Computing Blog"
    
    [[params.navlinks]]
    name = "About"
    url = "about"
    
    [[params.navlinks]]
    name = "Blog"
    url = ""
    
    [[params.navlinks]]
    name = "Tutorials"
    url = "tutorial/"
